version: '3'
services:
  db-web:
    container_name: go-api-db
    image: percona
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_USER=${USERNAME_DB}
      - MYSQL_ROOT_PASSWORD=${PASSWORD_DB}
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "20"

## MIGRATION TOOL
  db-migration:
    container_name: go-api-migration
    image: flyway/flyway
    tty: true
    # command: -locations="filesystem:/flyway/sql" -url=jdbc:mysql://db-web:3306/${DATABASE_NAME} -user=${USERNAME_DB} -password=${PASSWORD_DB} -connectRetries=10 info
    command: -locations="filesystem:/flyway/sql" -url=jdbc:mysql://db-web:3306/${DATABASE_NAME} -user=${USERNAME_DB} -password=${PASSWORD_DB} -connectRetries=10 migrate
    volumes:
      - ./database_migration/mysql:/flyway/sql
    working_dir: /flyway/sql
    depends_on:
      - db-web

  redis:
    container_name: go-api-redis
    image: redis
    ports:
      - "${REDIS_SESSION_PORT}:6379"
    command: --requirepass root

  mail:
    container_name: go-api-mail
    image: sj26/mailcatcher
    ports:
      - "${SMTP_PORT}:1025"
      - "1080:1080"

  rabbit:
    container_name: go-api-rabbit
    image: rabbitmq:3-management
    ports:
      - "${RABBIT_PORT}:5672"
      - "2153:15672"

  elastic-search:
    container_name: go-api-elasticsearch
    image: elasticsearch:7.4.2
    ports:
      - "${ELASTIC_PORT}:9200"
      - "3900:9300"
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - go-api-network

networks:
  go-api-network:
    driver: bridge
