package models

// M : Mandatory
// O : Optional
// C : Conditional

/*
CallbacksFasPay
| Parameter      | Data Type        | M/O/C | Description                                                                                                                                              |
|----------------|------------------|-------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| merchant_id    | Numeric (15)     | M     | Merchant Code                                                                                                                                            |
| bill_no        | Alfanumeric (32) | M     | Order Number                                                                                                                                             |
| Request        | Alfanumeric (50) | O     | Request Name                                                                                                                                             |
| trx_id         | Numeric (16)     | M     | Transaction ID (Issued/generated by Faspay (Media Indonusa)) Notes: Unique Transaction ID for 1 day or as long as it hasn't been paid and hasn't expired |
| bill_reff      | Alfanumeric (20) | M     | bill_refference                                                                                                                                          |
| bill_total     | Numeric          | M     | bill_total                                                                                                                                               |
| payment_reff   | Alfanumeric (16) | O     | Payment reference                                                                                                                                        |
| Payment_date   | Datetime         | M     | Payment date                                                                                                                                             |
| bank_user_name | Alfanumeric (40) | M     | Channel customer name                                                                                                                                    |
| Status         | Char (1)         | M     | Payment status                                                                                                                                           |
| Signature      | Alfanumeric      | M     | Sha1(md5(user_id+password + bill_no + payment_status_code))                                                                                              |

Example CallbacksFasPay:
{
  "merchant_id":99999,
  "bill_no":"4370",
  "request":"",
  "trx_id":8985999990013136,
  "bill_ref":"4370",
  "bill_total":10000,
  "payment_reff":"",
  "payment_date":"2016-07-22 14:59:30",
  "bank_user_name":"FaspayTest",
  "merchant":"FASPAY STORE",
  "status":"0",
  "signature":"0da33ad07fe9980f7b7ff70a964803e821a86866"
}
*/
type CallbacksFasPay struct {
	MerchantId   int    `json:"merchant_id"`
	BillNo       string `json:"bill_no"`
	Request      string `json:"request"`
	TrxId        int64  `json:"trx_id"`
	BillRef      string `json:"bill_ref"`
	BillTotal    int    `json:"bill_total"`
	PaymentReff  string `json:"payment_reff"`
	PaymentDate  string `json:"payment_date"`
	BankUserName string `json:"bank_user_name"`
	Merchant     string `json:"merchant"`
	Status       string `json:"status"`
	Signature    string `json:"signature"`
}
