package models

// M : Mandatory
// O : Optional
// C : Conditional

/*
CancelTransactionRequest
| Parameter      | Data Type        | M/O/C | Description                                                                                                                                              |
|----------------|------------------|-------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| Request        | Alfanumeric (50) | O     | Request Description                                                                                                                                      |
| trx_id         | Numeric (16)     | M     | Transaction ID (Issued/generated by Faspay (Media Indonesia)) Notes: Unique Transaction ID for 1 day or as long as it hasn't been paid and hasn't expired |
| merchant_id    | Numeric (5)      | M     | Merchant Code                                                                                                                                            |
| Merchant       | Alfanumeric (32) | O     | Merchant Name                                                                                                                                            |
| bill_no        | Alfanumeric (32) | M     | Order Number                                                                                                                                             |
| payment_cancel | Alfanumeric (50) | M     | Cancellation Description                                                                                                                                 |
| Signature      | Alfanumeric      | M     | sha1(md5(user_id+password+bill_no))                                                                                                                      |


Example CancelTransactionRequest:
{
 "request":"Canceling Payment",
 "trx_id":"9999970700002782",
 "merchant_id":"99999",
 "merchant" : "FASPAY STORE",
 "bill_no":"8226",
 "payment_cancel" : "Barang Habis",
 "signature":"6d16537c525b0e8450cdf5d4e67fbc24b1ed41c5"
}
*/
type CancelTransactionRequest struct {
	Request       string `json:"request"`
	TrxId         string `json:"trx_id"`
	MerchantId    string `json:"merchant_id"`
	Merchant      string `json:"merchant"`
	BillNo        string `json:"bill_no"`
	PaymentCancel string `json:"payment_cancel"`
	Signature     string `json:"signature"`
}

/*
CancelTransactionResponse
| Parameter           | Data Type        | M/O/C | Description                                                                                                                                              |
|---------------------|------------------|-------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| Response            | Alfanumeric (50) | O     | Request Description                                                                                                                                      |
| trx_id              | Numeric (16)     | M     | Transaction ID (Issued/generated by Faspay (Media Indonesia)) Notes: Unique Transaction ID for 1 day or as long as it hasn't been paid and hasn't expired |
| merchant_id         | Numeric (5)      | M     | Merchant Code                                                                                                                                            |
| Merchant            | Alfanumeric (32) | O     | Merchant Name                                                                                                                                            |
| bill_no             | Alfanumeric (32) | M     | Order Number                                                                                                                                             |
| trx_status_code     | Numeric          | M     | Transaction Status                                                                                                                                       |
| trx_status_desc     | Alfanumeric (32) | M     | Transaction Status Description                                                                                                                           |
| payment_status_code | Numeric (1)      | M     | Payment status code                                                                                                                                      |
| payment_status_desc | Alfanumeric (32) | M     | Payment Status Description                                                                                                                               |
| payment_cancel_msg  | Alfanumeric (50) | M     | Payment Cancel Reason's Message                                                                                                                          |
| payment_cancel_date | Datetime         | M     | Payment Cancel Date                                                                                                                                      |
| response_code       | Alfanumeric (2)  | M     | Response Code 00 Success                                                                                                                                 |
| response_desc       | Alfanumeric (32) | M     | Response Description                                                                                                                                     |

Example CancelTransactionResponse:
{
    "response": "Canceling Payment",
    "trx_id": "9999970700002782",
    "merchant_id": "99999",
    "merchant": "FASPAY STORE",
    "bill_no": "8226",
    "trx_status_code": "3",
    "trx_status_desc": "Order Expired",
    "payment_status_code": "7",
    "payment_status_desc": "Payment Expired",
    "payment_cancel_date": [],
    "payment_cancel": "Barang Habis",
    "response_code": "54",
    "response_desc": "Transaksi Anda telah kedaluwarsa."
}
*/
type CancelTransactionResponse struct {
	Response          string        `json:"response"`
	TrxId             string        `json:"trx_id"`
	MerchantId        string        `json:"merchant_id"`
	Merchant          string        `json:"merchant"`
	BillNo            string        `json:"bill_no"`
	TrxStatusCode     string        `json:"trx_status_code"`
	TrxStatusDesc     string        `json:"trx_status_desc"`
	PaymentStatusCode string        `json:"payment_status_code"`
	PaymentStatusDesc string        `json:"payment_status_desc"`
	PaymentCancelDate []interface{} `json:"payment_cancel_date"`
	PaymentCancel     string        `json:"payment_cancel"`
	ResponseCode      string        `json:"response_code"`
	ResponseDesc      string        `json:"response_desc"`
}
