package models

/*
PaymentNotificationRequest
| Parameter           | Data Type                    | M/O/C | Description                                                                                                                                                      |
|---------------------|------------------------------|-------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| request             | Alfanumeric (50)             | O     | Request Description                                                                                                                                              |
| trx_id              | Numeric (16)                 | M     | Transaction ID (Issued/generated by Faspay (Media Indonesia)) Notes: Unique Transaction ID for 1 day or as long as it hasn't been paid and hasn't expired         |
| merchant_id         | Numeric (5)                  | M     | Merchant Code                                                                                                                                                    |
| merchant            | Alfanumeric (32)             | M     | Merchant Name                                                                                                                                                    |
| bill_no             | Alfanumeric (32)             | M     | Order Number                                                                                                                                                     |
| payment_reff        | Alfanumeric (32)             | O     | would be fill if the payment has been made                                                                                                                       |
| payment_date        | Datetime YYYY-MM-DD HH:MM:SS | M     | customer payment date would be fill if the payment has been made                                                                                                 |
| payment_status_code | Char (1)                     | M     | Payment Status 0 Unprocessed 1 In Process 2 Payment Success 3 Payment Failed 4 Payment Reversal 5 No bills found 7 Payment Expired 8 Payment Cancelled 9 Unknown |
| payment_status_desc | Alfanumeric (32)             | M     | Payment description                                                                                                                                              |
| bill_total          | Numeric                      | M     | Billing total of transaction                                                                                                                                     |
| payment_total       | Numeric                      | M     | Payment total of transaction                                                                                                                                     |
| payment_channel_uid | Numeric                      | M     | Payment channel code                                                                                                                                             |
| payment_channel     | Alfanumeric (32)             | M     | Payment channel description                                                                                                                                      |
| signature           | Alfanumeric                  | M     | Sha1(md5(user_id+password + bill_no + payment_status_code))                                                                                                      |

Example PaymentNotificationRequest:
{
  "request": "Payment Notification",
  "trx_id": "3183540500001172",
  "merchant_id": "31835",
  "merchant": "Panin Asset Management",
  "bill_no": "220171004154635022158001",
  "payment_reff": "null",
  "payment_date": "2017-10-04 15:46:35",
  "payment_status_code": "2",
  "payment_status_desc": "Payment Sukses",
  "bill_total": "5000000",
  "payment_total": "5000000",
  "payment_channel_uid": "402",
  "payment_channel": "Permata Virtual Account",
  "signature": "075c4983ba9883d41e1b3eab0de580dfc73d875b"
}
*/
type PaymentNotificationRequest struct {
	Request           string `json:"request"`
	TrxId             string `json:"trx_id"`
	MerchantId        string `json:"merchant_id"`
	Merchant          string `json:"merchant"`
	BillNo            string `json:"bill_no"`
	PaymentReff       string `json:"payment_reff"`
	PaymentDate       string `json:"payment_date"`
	PaymentStatusCode string `json:"payment_status_code"`
	PaymentStatusDesc string `json:"payment_status_desc"`
	BillTotal         string `json:"bill_total"`
	PaymentTotal      string `json:"payment_total"`
	PaymentChannelUid string `json:"payment_channel_uid"`
	PaymentChannel    string `json:"payment_channel"`
	Signature         string `json:"signature"`
}

/*
PaymentNotificationResponse
| Parameter     | Data Type        | M/O/C | Description                                                                                                                                              |
|---------------|------------------|-------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| trx_id        | Numeric (16)     | M     | Transaction ID (Issued/generated by Faspay (Media Indonesia)) Notes: Unique Transaction ID for 1 day or as long as it hasn't been paid and hasn't expired |
| merchant_id   | Numeric (15)     | M     | Channel Code From Faspay                                                                                                                                 |
| bill_no       | Alfanumeric (32) | M     | Order Number                                                                                                                                             |
| response_code | Alfanumeric (2)  | M     | Response code                                                                                                                                            |
| response_desc | Alfanumeric (50) | M     | Response Description                                                                                                                                     |
| response_date | Datetime         | M     | Response date                                                                                                                                            |

Example PaymentNotificationResponse:
{
    "response": "Payment Notification",
    "trx_id": "3183540500001172",
    "merchant_id": "31835",
    "merchant": "Panin Asset Management",
    "bill_no": "220171004154635022158001",
    "response_code": "00",
    "response_desc": "Success",
    "response_date": "2017-10-05 16:53:10"
}
*/
type PaymentNotificationResponse struct {
	Response     string `json:"response"`
	TrxId        string `json:"trx_id"`
	MerchantId   string `json:"merchant_id"`
	Merchant     string `json:"merchant"`
	BillNo       string `json:"bill_no"`
	ResponseCode string `json:"response_code"`
	ResponseDesc string `json:"response_desc"`
	ResponseDate string `json:"response_date"`
}
