package models

// M : Mandatory
// O : Optional
// C : Conditional

/*
RedirectProcessParam
| Parameter   | Data Type        | M/O/C  | Description                                                                                                                                              |
|-------------|------------------|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| trx_id      | Numeric (16)     | M      | Transaction ID (Issued/generated by Faspay (Media Indonesia)) Notes: Unique Transaction ID for 1 day or as long as it hasn't been paid and hasn't expired |
| Merchant_id | Numeric (5)      | M      | Merchant Code                                                                                                                                            |
| bill_no     | Alfanumeric (16) | M      | Order Number                                                                                                                                             |
| Signature   | Alfanumeric      | M      | sha1(md5((user_id + password + bill_no))                                                                                                                 |

Template: RedirectProcessDev/signature?trx_id=&merchant_id=&bill_no=
Example RedirectProcessParam:
https://debit-sandbox.faspay.co.id/pws/100003/0830000010100000/e0ba1b2dc29ab4cb4221df092f44b1c4e6f45c63?trx_id=3100440033666278&merchant_id=31004&bill_no=31004001
*/
type RedirectProcessParam struct {
	TrxID      int    `json:"trx_id"`
	MerchantID int    `json:"merchant_id"`
	BillNo     string `json:"bill_no"`
	Signature  string `json:"signature"`
}
